### ISSUE TITLE
LCARS and Switch lightning files

### ISSUE THREAD

**Issue by arhmnsh** [svohr/fs_edge_rgb#1]
Hi!
What are the LCARS and Switch files in the lightning folder? How can we use these themes/files?

**Comment by svohr** [comment]
They're color schemes I use that I generated with the python script. The "LCARS" theme sets the LEDs to a yellow/orange/blue scheme by key grouping and the "switch" scheme sets LEDs blue on the left, red on the right like the Joy-Cons on a Nintendo Switch. As far as I know the keyboard only recognizes configuration files in the `led[1-9].txt` form, so to use them you have to rename the custom lighting file to one of the `led` filenames and overwrite the previous setting.
